name: Run_Javascript

on:
  workflow_dispatch:

jobs:
  practice:
    runs-on: ubuntu-24.04
    env:
      myName : Khai
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 22 
      - run: node testAuto.js
      - run: pwd
      - run: echo "${{github.actor}} is $myName $myName"