name: Test_Email_Sender

on:
  workflow_dispatch:

jobs:
  autoEmail:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: 22
      - run: ls 
      - run: cd backend
      - run: pwd
      - run: ls
      - run: npm install
      - run: cd ..
      - run: node automation/auto.js